#!/usr/bin/env bash
#
# build-css.sh — Concatenate all render-blocking CSS into a single file.
#
# Eliminates the @import waterfall that kills mobile FCP.
# Before: 14 sequential HTTP requests (~1500ms on 4G)
# After:  1 request (~100ms on 4G)
#
# Usage:
#   ./scripts/build-css.sh          # build only
#   ./scripts/build-css.sh --watch  # rebuild on file changes (requires inotifywait)
#
# Output: assets/css/gcube.built.css
#
# The enqueue.php automatically detects this file and loads it instead of
# the individual CSS files. Delete it to return to dev mode (@imports).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GCUBE_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="${GCUBE_DIR}/assets/css/gcube.built.css"

# Parent theme lives alongside gCube. The deployed install dir is
# "gTemplate" (/opt/geodineum/gTemplate, same in ~/gh dev checkouts);
# "gTemplate-wp" is a legacy checkout name kept as a fallback.
PARENT_DIR=""
for candidate in "${GCUBE_DIR}/../gTemplate" "${GCUBE_DIR}/../gTemplate-wp"; do
    if [ -d "$candidate" ]; then
        PARENT_DIR="$candidate"
        break
    fi
done
if [ -z "$PARENT_DIR" ]; then
    echo "Error: Parent theme not found at ${GCUBE_DIR}/../gTemplate (or ../gTemplate-wp)"
    exit 1
fi

build() {
    local tmpfile
    tmpfile=$(mktemp)

    cat > "$tmpfile" <<'HEADER'
/**
 * gCube Built CSS — DO NOT EDIT
 *
 * Auto-generated by scripts/build-css.sh
 * Edit the source files in assets/css/ and rebuild.
 *
 * Contains (in order):
 *   1. Parent: fonts.css (@font-face declarations)
 *   2. Parent: golden-typography.css (type scale, spacing, utilities)
 *   3. Parent: geodineum-content.css (.geo page-content system)
 *   4. Child:  variables.css (cube CSS custom properties)
 *   5. Child:  animations.css (@keyframes)
 *   6. Child:  cube-structure.css (3D transforms)
 *   7. Child:  cube-surfaces.css (dual-surface pseudo-elements)
 *   8. Child:  face-content.css (content layout, scrolling)
 *   9. Child:  face-expansion.css (fullscreen reading mode)
 *  10. Child:  navigation.css (nav buttons)
 *  11. Child:  typography.css (cube text styles)
 *  12. Child:  content-types.css (posts, glass mode)
 *  13. Child:  responsive.css (media queries)
 */

HEADER

    # --- Parent theme CSS ---

    # fonts.css: rewrite font paths from ../fonts/ to point to parent theme
    # In WordPress, the built file loads from the child theme, so font paths
    # need to reference the child's own fonts/ directory (identical copies).
    echo "/* === fonts.css (parent: @font-face declarations) === */" >> "$tmpfile"
    cat "${PARENT_DIR}/assets/css/fonts.css" >> "$tmpfile"
    echo "" >> "$tmpfile"

    echo "/* === golden-typography.css (parent: type scale + utilities) === */" >> "$tmpfile"
    cat "${PARENT_DIR}/assets/css/golden-typography.css" >> "$tmpfile"
    echo "" >> "$tmpfile"

    echo "/* === geodineum-content.css (parent: .geo content system) === */" >> "$tmpfile"
    cat "${PARENT_DIR}/assets/css/geodineum-content.css" >> "$tmpfile"
    echo "" >> "$tmpfile"

    # --- Child theme CSS (in main.css @import order) ---
    local child_css_dir="${GCUBE_DIR}/assets/css"
    local modules=(
        variables.css
        animations.css
        cube-structure.css
        cube-surfaces.css
        face-content.css
        face-expansion.css
        navigation.css
        typography.css
        content-types.css
        responsive.css
    )

    for module in "${modules[@]}"; do
        if [ ! -f "${child_css_dir}/${module}" ]; then
            echo "Warning: ${module} not found, skipping" >&2
            continue
        fi
        echo "/* === ${module} === */" >> "$tmpfile"
        cat "${child_css_dir}/${module}" >> "$tmpfile"
        echo "" >> "$tmpfile"
    done

    mv "$tmpfile" "$OUTPUT"

    local size
    size=$(wc -c < "$OUTPUT")
    local size_kb=$((size / 1024))
    echo "Built ${OUTPUT} (${size_kb}KB)"
}

# Run build
build

# Optional watch mode
if [ "${1:-}" = "--watch" ]; then
    if ! command -v inotifywait &>/dev/null; then
        echo "Watch mode requires inotifywait (apt install inotify-tools)"
        exit 1
    fi

    echo "Watching for CSS changes..."
    while inotifywait -q -e modify \
        "${GCUBE_DIR}/assets/css/"*.css \
        "${PARENT_DIR}/assets/css/fonts.css" \
        "${PARENT_DIR}/assets/css/golden-typography.css" \
        "${PARENT_DIR}/assets/css/geodineum-content.css" 2>/dev/null; do
        echo "Change detected, rebuilding..."
        build
    done
fi
