<?php
declare(strict_types=1);
/**
 * Asset Enqueue
 *
 * Handles CSS and JavaScript loading for the theme.
 *
 * @package    gCube
 * @subpackage Assets
 * @since      2.0.0
 *
 * @dependencies constants.php (GCUBE_DIR, GCUBE_URI)
 * @dependents   None (registers WordPress hooks)
 *
 * @hooks
 *   - wp_enqueue_scripts: gcube_enqueue_assets()
 *
 * CSS Architecture (SRP-based modules):
 * - main.css: Aggregator that @imports all module files
 * - variables.css: CSS custom properties
 * - cube-structure.css: 3D transforms, positioning
 * - cube-surfaces.css: Dual-surface pseudo-elements
 * - face-content.css: Content containers, scrolling
 * - face-expansion.css: Fullscreen reading mode
 * - navigation.css: Nav buttons, wrappers
 * - typography.css: Fonts, text styles
 * - content-types.css: Posts, slugs, glass mode
 * - responsive.css: Media queries
 */

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Enqueue theme styles and scripts
 *
 * @since 1.0.0
 * @return void
 */
function gcube_enqueue_assets(): void {
    $theme_uri = GCUBE_URI;
    $theme_dir = GCUBE_DIR;
    $version = GCUBE_VERSION;

    // Built CSS: single file containing parent + child CSS (no @import waterfall).
    // Generated by scripts/build-css.sh. Falls back to main.css @imports in dev.
    $built_css_path = $theme_dir . '/assets/css/gcube.built.css';

    if (file_exists($built_css_path)) {
        $css_version = filemtime($built_css_path);

        // Single file replaces: parent fonts.css + golden-typography.css + child main.css
        wp_enqueue_style(
            'gcube-built-css',
            $theme_uri . '/assets/css/gcube.built.css',
            [],
            $css_version
        );

        // Dequeue parent CSS (already bundled in built file)
        wp_dequeue_style('gtemplate-golden-typography');
        wp_dequeue_style('gtemplate-geodineum-content');
        wp_dequeue_style('gtemplate-fonts');
    } else {
        // Dev mode: use @imports (slower on mobile, easier to debug)
        $main_css_path = $theme_dir . '/assets/css/main.css';
        $css_version = file_exists($main_css_path) ? filemtime($main_css_path) : $version;

        wp_enqueue_style(
            'gcube-main-css',
            $theme_uri . '/assets/css/main.css',
            [],
            $css_version
        );
    }

    // Enqueue cube controls JavaScript (CRITICAL for rotation/interaction)
    wp_enqueue_script(
        'gcube-cube-controls',
        $theme_uri . '/assets/js/cube-controls.js',
        [],
        $version,
        ['in_footer' => true, 'strategy' => 'defer']
    );

    // Pass customizer settings to JavaScript for expansion feature
    wp_localize_script('gcube-cube-controls', 'gcubeSettings', gcube_get_js_settings());

    // Dequeue parent's PWA loader (gCube has its own)
    wp_dequeue_script('gtemplate-pwa-loader');

    // Enqueue PWA loader
    wp_enqueue_script(
        'gcube-pwa-loader',
        $theme_uri . '/assets/js/pwa-loader.js',
        [],
        $version,
        ['in_footer' => true, 'strategy' => 'defer']
    );
}
// Priority 20: must run AFTER parent's enqueue (priority 10) to dequeue parent CSS
add_action('wp_enqueue_scripts', 'gcube_enqueue_assets', 20);

/**
 * Light/dark toggle is not ready on the cube yet. Runs at wp_head:2, right after
 * the parent's pre-paint boot (wp_head:1): overrides any persisted light choice
 * back to the brand dark ground (no flash) and sets data-geo-no-theme-toggle so
 * the parent geo-behaviors.js skips mounting the floating toggle.
 */
function gcube_lock_dark_theme(): void {
    echo '<script>(function(){var r=document.documentElement;r.setAttribute("data-theme","dark");r.setAttribute("data-geo-no-theme-toggle","");})();</script>' . "\n";
}
add_action('wp_head', 'gcube_lock_dark_theme', 2);

/**
 * Get JavaScript settings from Customizer
 *
 * @since 2.0.0
 * @return array Settings for wp_localize_script
 */
function gcube_get_js_settings(): array {
    // gtemplate_expand_* are the parent-registered settings (the old
    // gcube_expand_* reads pointed at names nothing registers)
    return [
        'expandMode' => get_theme_mod('gtemplate_expand_mode', 'focus'),
        'expandEnabled' => (bool) get_theme_mod('gtemplate_expand_enabled', true),
        'showCloseButton' => (bool) get_theme_mod('gtemplate_expand_show_close', true),
        'showHint' => (bool) get_theme_mod('gtemplate_expand_show_hint', true),
        'maxZoom' => (int) get_theme_mod('gCore_max_zoom', 90),
    ];
}
